spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: user

  application:
    name: PRODUCTS-SERVICE
    server:
      port: 8082


  eureka:
    instance:
      prefer-ip-address: true
    client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
        defaultZone: http://localhost:8761/eureka